// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtyklsfzvdprjkbuckoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0eWtsc2Z6dmRwcmprYnVja296Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NDkzOTksImV4cCI6MjA2OTQyNTM5OX0.MWJfweLRYX6f5HfD7irPhUkHJ1gF5wNo9G2JdF-xamo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});